module: "TLoop"
merge_logic: "merge-wt"
device_id: -1 #0
epochs: 10
train_data:
  file: "./DATA/mnist//train.txt"
  dataset: "gensvm"
  gensvm:
    dimension: 784
    centering_info: "./DATA/mnist/centering_info.npz"
  sampler: "simple"
  simple:
    batch_size: 64
progress_test_data:
  file: "./DATA/mnist//test.txt"
  dataset: "gensvm"
  gensvm:
    dimension: 784
    centering_info: "./DATA/mnist/centering_info.npz"
  sampler: "simple"
  simple:
    batch_size: 1000
model:
  name: "ROASTCNN"
  ROASTCNN:
    in_channels: 1
    out_channels: 20
    num_layers: 3
    hidden_size: 100
    num_class: 10
    kernel_size: 5
    compression: 0.5
    seed: 101
optimizer:
  name: "adam"
  adam:
    lr: 0.001
    weight_decay: 0
loss:
  name: "NLL"
progress_evaluator:
  name: "simple_print"
  simple_print:
      eval_itr: 1000000
      eval_epoch: 1
      skip_0: 1
      csv_dump: "./DATA/mnist/record/log.train.csv"
